pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', 
                url: 'https://github.com/hdewan63/cicd-end-to-end',
                branch: 'main'
           }
        }

      stage('Build Docker') {
          steps {
              script {
                  sh "docker build -t hddewan/cicd-e2e:${BUILD_NUMBER} ."
              }
          }
      }
      stage('Push the artifacts') {
          steps {
              script {
                  withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable:
       'DOCKER_PASS')]) {
                      sh "echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin"
                      sh "docker push hddewan/cicd-e2e:${BUILD_NUMBER}"
                  }
              }
          }
      }
        
        
      stage('Update K8S manifest & push to Repo'){
          steps {
              script{
                  withCredentials([usernamePassword(credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', passwordVariable:
       'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                      sh """
                      git clone https://\${GIT_USERNAME}:\${GIT_PASSWORD}@github.com/hdewan63/Jenkins-Zero-To-Hero.git
                      cd Jenkins-Zero-To-Hero/python-jenkins-argocd-k8s/deploy
                      sed -i "s|image: hddewan/cicd-e2e:.*|image: hddewan/cicd-e2e:${BUILD_NUMBER}|g" deploy.yaml
                      git add deploy.yaml
                      git commit -m 'Updated image to ${BUILD_NUMBER}'
                      git push
                      """
                  }
              }
          }
      }
    }
}
